Models/Article/Article_Category_Data.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
namespace WebSite
{
    public class Article_Category_Data
    {
        /// <summary>
        /// List chỉ hiển thị
        /// </summary>
        /// <param name="PartnerNumber"></param>
        /// <param name="Message"></param>
        /// <returns></returns>
        public static List<Article_Category_Model> ListAsMenu(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = @"
WITH R AS 
( 
    SELECT CategoryKey, CategoryName AS NAME1, Description, Publish, 
    PARENT, DEPTH = 0, SORT = CAST(CategoryKey AS VARCHAR(MAX)) 
    FROM PDT_Article_Category 
    WHERE RecordStatus <> 99 
    AND Parent = 0 
    AND PartnerNumber = @PartnerNumber 
    AND Publish = 'TRUE'
    UNION ALL
    SELECT Sub.CategoryKey, Sub.CategoryName AS NAME1, Sub.Description, Sub.Publish, 
    Sub.PARENT, DEPTH = R.DEPTH + 1, SORT = R.SORT + '-' + CAST(Sub.CategoryKey AS VARCHAR(MAX)) 
    FROM R INNER JOIN PDT_Article_Category Sub ON R.CategoryKey = Sub.Parent 
    WHERE RecordStatus <> 99 
    AND PartnerNumber = @PartnerNumber
    AND Sub.Publish = 'TRUE'
)
SELECT CategoryName = R.[NAME1], R.CategoryKey, R.Description, R.Publish, R.SORT, R.DEPTH, R.Parent 
FROM R ORDER BY SORT  ";
            string zConnectionString = TN_Helper.ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Article_Category_Model> zList = new List<Article_Category_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Article_Category_Model()
                {
                    CategoryKey = r["CategoryKey"].ToInt(),
                    CategoryName = r["CategoryName"].ToString(),
                    Description = r["Description"].ToString(),
                    Parent = r["Parent"].ToInt(),
                    Publish = r["Publish"].ToBool(),
                    Level = r["SORT"].ToInt(),
                });
            }
            return zList;
        }

        /// <summary>
        /// List xem xoá sửa
        /// </summary>
        /// <param name="PartnerNumber"></param>
        /// <param name="Message"></param>
        /// <returns></returns>
        public static List<Article_Category_Model> ListCategory(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = "WITH R AS ( " +
                " SELECT CategoryKey, CategoryName, Description, Publish, PARENT, DEPTH = 0, SORT = CAST(CategoryKey AS VARCHAR(MAX)), Rank"
            + " FROM PDT_Article_Category "
            + " WHERE RecordStatus <> 99 "
            + " AND Parent = 0 "
            + " AND PartnerNumber = @PartnerNumber "
            + " UNION ALL "
            + " SELECT Sub.CategoryKey, Sub.CategoryName, Sub.Description, Sub.Publish, Sub.PARENT, DEPTH = R.DEPTH + 1, SORT = R.SORT + '-' + CAST(Sub.CategoryKey AS VARCHAR(MAX)), Sub.Rank"
            + " FROM R INNER JOIN PDT_Article_Category Sub ON R.CategoryKey = Sub.Parent "
            + " WHERE RecordStatus <> 99 "
            + " AND PartnerNumber = @PartnerNumber) "
            + " SELECT CategoryName = REPLICATE('---', R.DEPTH * 1) + R.CategoryName, R.CategoryKey, R.Description, R.Publish, R.SORT, R.DEPTH, R.Parent, R.Rank "
            + " FROM R ORDER BY SORT, Rank ";
            string zConnectionString = TN_Helper.ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Article_Category_Model> zList = new List<Article_Category_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Article_Category_Model()
                {
                    CategoryKey = r["CategoryKey"].ToInt(),
                    CategoryName = r["CategoryName"].ToString(),
                    Description = r["Description"].ToString(),
                    Parent = r["Parent"].ToInt(),
                    Publish = r["Publish"].ToBool(),
                    Level = r["SORT"].ToInt(),
                    Rank = r["Rank"].ToInt(),
                });
            }
            return zList;
        }
    }
}

Models/Article/Article_Category_Model.cs
using System;
namespace WebSite
{
    public class Article_Category_Model
    {
        #region [ Field Name ]
        private string _WebUrl = "";
        private int _Slug = 0;
        private int _CategoryKey = 0;
        private string _CategoryName = "";
        private string _Description = "";
        private string _Image = "";
        private int _Parent = 0;
        private int _Rank = 0;
        private bool _Publish;
        private bool _Activate;
        private int _Level = 0;
        private string _CategoryPath = "";
        private string _PartnerNumber = "";
        private int _RecordStatus = 0;
        private DateTime _CreatedOn = DateTime.MinValue;
        private string _CreatedBy = "";
        private string _CreatedName = "";
        private DateTime _ModifiedOn = DateTime.MinValue;
        private string _ModifiedBy = "";
        private string _ModifiedName = "";
        #endregion

        #region [ Properties ]
        public int CategoryKey
        {
            get { return _CategoryKey; }
            set { _CategoryKey = value; }
        }
        public string CategoryName
        {
            get { return _CategoryName; }
            set { _CategoryName = value; }
        }
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }
        public string Image
        {
            get { return _Image; }
            set { _Image = value; }
        }
        public int Parent
        {
            get { return _Parent; }
            set { _Parent = value; }
        }
        public int Rank
        {
            get { return _Rank; }
            set { _Rank = value; }
        }
        public bool Publish
        {
            get { return _Publish; }
            set { _Publish = value; }
        }
        public bool Activate
        {
            get { return _Activate; }
            set { _Activate = value; }
        }
        public int Level
        {
            get { return _Level; }
            set { _Level = value; }
        }
        public string CategoryPath
        {
            get { return _CategoryPath; }
            set { _CategoryPath = value; }
        }
        public string PartnerNumber
        {
            get { return _PartnerNumber; }
            set { _PartnerNumber = value; }
        }
        public int RecordStatus
        {
            get { return _RecordStatus; }
            set { _RecordStatus = value; }
        }
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { _CreatedOn = value; }
        }
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set { _CreatedBy = value; }
        }
        public string CreatedName
        {
            get { return _CreatedName; }
            set { _CreatedName = value; }
        }
        public DateTime ModifiedOn
        {
            get { return _ModifiedOn; }
            set { _ModifiedOn = value; }
        }
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set { _ModifiedBy = value; }
        }
        public string ModifiedName
        {
            get { return _ModifiedName; }
            set { _ModifiedName = value; }
        }

        public int Slug
        {
            get
            {
                return _Slug;
            }

            set
            {
                _Slug = value;
            }
        }

        public string WebUrl
        {
            get
            {
                return _WebUrl;
            }

            set
            {
                _WebUrl = value;
            }
        }
        #endregion
    }
}

Component/FrontEnd/BannerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class BannerViewComponent: ViewComponent
    {
       
        public IViewComponentResult Invoke()
        {
            var zList = Banner_Data.List(TN_Helper.PartnerNumber, out _);
            zList = zList.Where(s => s.Publish == true).ToList();
            return View("~/Views/Shared/Components/Banner.cshtml", zList);
        }
    }
}

Component/FrontEnd/IntroViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace WebSite.Component
{
    [ViewComponent]
    public class IntroViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(string ID)
        {
            var zInfo = new Config_Info(ID, TN_Helper.PartnerNumber);
            ViewBag.Title = zInfo.Config.Name;

            var zParent = zInfo.Config.ConfigKey;

            var zList = Config_Data.List(TN_Helper.PartnerNumber, zParent, out _);
            var zRecord = zList.SingleOrDefault(s => s.ConfigID == "COT1");

            var Blog = new Article_Model();
            if (zRecord != null)
            {
                string Key = zRecord.Value;
                Blog = new Article_Info(Key).Article;
            }

            ViewBag.Blog = Blog;

            zRecord = zList.SingleOrDefault(s => s.ConfigID == "COT2");
            Blog = new Article_Model();
            if (zRecord != null)
            {
                string Key = zRecord.Value;
                Blog = new Article_Info(Key).Article;
            }
            ViewBag.Youtube = Blog;

            return View("~/Views/Shared/Components/Intro.cshtml");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _Iconfiguration;

        public HomeController(ILogger<HomeController> logger, IConfiguration iconfiguration)
        {
            _logger = logger;
            _Iconfiguration = iconfiguration;

            TN_Helper.ConnectionString = _Iconfiguration.GetSection("Data").GetSection("ConnectionString").Value;
            TN_Helper.PartnerNumber = _Iconfiguration.GetSection("PartnerNumber").Value;
        }

        public IActionResult Index()
        {


            return View();
        }

        [Route("bai-viet/{ArticleID}")]
        public IActionResult Article(string ArticleID)
        {
            var zInfo = new Article_Info();
            zInfo.Get_ArticleID(ArticleID);
            if (zInfo.Code == "404" ||
                zInfo.Article.Publish == false ||
                zInfo.Article.RecordStatus == 99)
            {
                return View("~/Views/Shared/404.cshtml");
            }

            ViewBag.CategoryName = new Article_Category_Info(zInfo.Article.CategoryKey).Article_Category.CategoryName;

            return View("~/Views/Home/Article.cshtml", zInfo.Article);
        }

        [Route("tin-tuc/{CategoryKey}")]
        public IActionResult Article_List(int CategoryKey)
        {
            ViewBag.CategoryName = new Article_Category_Info(CategoryKey).Article_Category.CategoryName;
            var zList = Article_Data.ListShow(TN_Helper.PartnerNumber, CategoryKey, out _);
            return View("~/Views/Home/Article_List.cshtml", zList);
        }

        [Route("lien-he")]
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("~/Views/Shared/404.cshtml", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            //return View();
        }

        [HttpPost]
        public JsonResult SendMail(string Email, string Name, string Title, string Content)
        {
            var zResult = new ServerResult();
            if (Email == null && Email == string.Empty)
            {
                zResult.Success = false;
                zResult.Message = "Mail không đúng định dạng !.";
                return Json(zResult);
            }

            Name ??= "";
            Title ??= "";
            Content ??= "";

            var zModel = new EmailModel
            {
                Email = _Iconfiguration.GetSection("MailInfo").GetSection("MailFrom").Value,
                Password = _Iconfiguration.GetSection("MailInfo").GetSection("Password").Value,
                To = _Iconfiguration.GetSection("MailInfo").GetSection("MailTo").Value,
            };

            if (Name != string.Empty &&
                Title != string.Empty &&
                Content != string.Empty)
            {
                string Body =
                   "Họ tên:" + Name + "<br/>" +
                   "Email: " + Email + "<br/>" +
                   "Nội dung:" + Content + "<br/>";

                zModel.Subject = Title;
                zModel.Body = Body;
            }
            else
            {
                Title = "Nhận đăng ký thông tin";
                string Body = "Nhận thông tin gửi đến mail:" + Email;
                zModel.Subject = Title;
                zModel.Body = Body;
            }

            zResult.Message = TN_Utils.SendGmail(zModel);
            return Json(zResult);
        }
    }
}

Views/Home/Article.cshtml
@using Microsoft.AspNetCore.Html
@model Article_Model
    <style>
        .fit-image {
            max-width: 350px !important;
        }
    </style>
    <div class="breadcrumbs-area position-relative mb-text-p">
        <div class="container" style="padding-top:30px">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="breadcrumb-content position-relative section-content">
                        <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">
                            @ViewBag.CategoryName
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portfolio-section pt-90">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12 order-lg-1">
                    <!-- Portfolio Details Content Start -->
                    <div class="portfolio-details-content" data-aos="fade-up" data-aos-delay="300">
                        <div class="portfolio-details-desc mb-8">
                            <h2 class="title text-center">@Model.ArticleName</h2>
                        </div>
                        <div class="mb-3">
                            @Model.Summarize
                        </div>
                        @if (Model.ImageLarge.Length > 0)
                        {
                            <div class="text-center mb-3">
                                <img src="@Url.Content(Model.ImageLarge)" class="fit-image" />
                            </div>
                        }
                        <div class="portfolio-details-info">
                            <ul>
                                <li id="divBlog">
                                    @(new HtmlString(Model.ArticleContent))
                                </li>

                                <li class="">
                                    <div class="meta-list mb-3">
                                        <a href="#" class="meta-item author">@Model.CreatedName</a>

                                        @if (Model.FileAttack.Length > 0)
                                        {
                                            <a href="@Model.FileAttack" download="" class="float-right" style="font-style: oblique;">
                                                Tập tin đính kèm
                                                <i class="fas fa-paperclip bounce3 animated3 "></i>
                                            </a>
                                        }

                                        <span class="meta-item date">@Model.ModifiedOn.ToString("dd/MM/yyyy")</span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Portfolio Details Content End -->
                </div>
                <div class="col-lg-4 col-12 order-lg-2" id="sticky-sidebar">
                    @await Component.InvokeAsync("LeftArticle", Model.CategoryKey)
                </div>
            </div>
        </div>
    </div>
    @section Scripts{
        <script>
            $(document).ready(function () {
                $("#divBlog table").each(function () {
                    $(this).addClass("table");
                });
                $("#divBlog ul").each(function () {
                    $(this).css("margin-left", "30px");
                });
            });
        </script>
    }

Views/Home/Article_List.cshtml
@model List<Article_Model>

<div class="breadcrumbs-area position-relative mb-text-p"
     style="
    background: url('/themes/frontend/images/Banner2.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    background-position: 0px -145px;
    padding-bottom:50px;">
    <div class="container" style="padding-top:30px">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">
                        @ViewBag.CategoryName
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blog-section pt-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-12">
                <div class="row mb-n10">
                    @{
                        if (Model.Count > 0)
                        {
                            for (int i = 0; i < Model.Count; i++)
                            {
                                #region [--FetchData--]
                                var zItem = Model[i];
                                string zDate = zItem.CreatedOn.ToString("dd/MM/yyyy");
                                string zAuthor = zItem.ModifiedName;
                                string zTitle = zItem.ArticleName;
                                string zSumamarize = zItem.Summarize;
                                string zID = zItem.ArticleID;

                                string zImg = zItem.ImageLarge;
                                if (zImg == string.Empty)
                                {
                                    zImg = "~/themes/frontend/images/noimage.svg";
                                }

                                string zLink = "/bai-viet/" + zID;
                                #endregion

                                <div class="col-sm-4 mb-4">
                                    <!-- Single Blog Post Start -->
                                    <div class="single-blog-post-wrap" data-aos="fade-up" data-aos-delay="200">
                                        <div class="blog-thumbnail">
                                            <a href="@zLink" style="height:300px; background-image: url('@Url.Content(zImg)'); background-size: contain; background-repeat: no-repeat; background-position: center;">
                                                <img class="btn-plus" src="@Url.Content("~/themes/frontend/images/icon/plus.svg")" alt="Plus Icons">
                                            </a>
                                        </div>
                                        <div class="blog-post-details pt-5">
                                            <h3 class="title">
                                                <a href="@zLink">
                                                    @zItem.ArticleName
                                                </a>
                                            </h3>
                                            <div class="post-meta mb-3 mt-3">
                                                <a href="@zLink">
                                                    <i class="fa fa-user"></i>
                                                    @zAuthor
                                                </a>
                                                <span>
                                                    <i class="fa fa-clock-o"></i>
                                                    @zDate
                                                </span>
                                            </div>
                                            <p class="desc-content desc-content1 mb-2 mb-md-5">@zItem.Summarize</p>
                                            <a href="@zLink" class="btn btn-hover-primary read-more">Xem thêm</a>
                                        </div>
                                    </div>
                                    <!-- Single Blog Post End -->
                                </div>
                            }
                        }
                        else
                        {
                            <h3>ĐANG CẬP NHẬT</h3>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "lien-he";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<div class="breadcrumbs-area position-relative mb-text-p"
     style=" background: url('/themes/frontend/images/banner-find-us.jpg'); background-size: cover; background-repeat: no-repeat; padding-bottom: 50px;">
    <div class="container" style="padding-top:30px">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">Liên hệ</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End Here -->
<!-- Contact Information And Title Area Start -->
<div class="contact-info mt-5 pt-90 pb-90">
    <div class="container">
        <div class="row mb-n10">
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="100">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-map-marker"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Địa chỉ</h4>
                        <span class="info-text"> Số 96/14 Tân Mỹ, KP.4,<br> P.Tân Thuận Tây, Q.7, TP.HCM, VIỆT NAM</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="300">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Điện thoại</h4>
                        <span class="info-text">
                            <a href="tel:0902106212 "> 0902 106 212 </a><br />
                            <a href="tel:02862706069">(028) 6270 6069</a>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="600">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-envelope-o"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Email</h4>
                        <span class="info-text">
                            <a href="mailto:info@tnsolution.vn">info@tnsolution.vn</a>
                            <br>
                            <a href="mailto:sales@tnsolution.vn">sales@tnsolution.vn</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact Information End -->
<!-- Contact Map Start -->
<div class="contac-map pb-90">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!--Google Map Area Start-->
                <div class="google-map-area">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.789355704406!2d106.71634341428684!3d10.75071136260881!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f1498bcc1c7%3A0xbaa2450999a48774!2zQ8OUTkcgVFkgQ-G7lCBQSOG6pk4gVE4gU09MVVRJT04!5e0!3m2!1sen!2s!4v1624411315225!5m2!1sen!2s" width="100%" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
                <!--Google Map Area Start-->
            </div>
        </div>
    </div>
</div>
<!-- Contact Map End -->
<!-- Contact Form Start -->
<div class="contact-form-area bg-light pt-90 pb-90" data-aos="fade-up" data-aos-delay="100">
    <div class="container">
        <div class="row">
            <div class="section-title text-center">
                <h1 class="title">KHI CẦN TƯ VẤN ĐỪNG NGẦN NGẠI !.</h1>
                <p class="mt-5 mb-5 pb-3">Để biết thêm thông tin chi tiết, vui lòng điền thông tin liên lạc bên dưới và chúng tôi sẽ liên lạc với quý khách sớm nhất !.</p>
            </div>
            <div class="offset-lg-2 col-lg-8">
                <div class="contact-form">

                    <div class="row">
                        <div class="col-md-6 col-12 mb-6">
                            <input class="input-item" type="text" placeholder="Họ tên *" name="name" id="txt_name">
                        </div>
                        <div class="col-md-6 col-12 mb-6">
                            <input class="input-item" type="email" placeholder="Email *" name="email" id="txt_email">
                        </div>
                        <div class="col-12 mb-6">
                            <input class="input-item" type="text" placeholder="Tiêu đề *" name="subject" id="txt_subject">
                        </div>
                        <div class="col-12 mb-6">
                            <textarea class="textarea-item" name="message" placeholder="Nội dung" id="txt_message"></textarea>
                        </div>
                        <div class="col-12 text-center">
                            <button class="btn btn-primary btn-hover-dark" type="button" id="btnSend">Gửi</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 form-messege text-center">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        var url = "@Url.Action("SendMail", "Home")";
        $("#btnSend").click(function () {
            $.ajax({
                url: url,
                type: 'POST',
                data: {
                    "Email": $("#txt_email").val(),
                    "Name": $("#txt_name").val(),
                    "Title": $("#txt_subject").val(),
                    "Content": $("#txt_message").val(),
                },
                beforeSend: function () {
                    $(".form-messege").empty();
                    $(".form-messege").text("Đang gửi mail");
                },
                success: function (r) {
                    $(".form-messege").empty();
                    $(".form-messege").append(r.message);
                    alert(r.message);
                },
                error: function (err) {
                    $(".form-messege").append(err.responseText);
                },
                complete: function () {

                }
            });
        });
    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!--Style for home only-->
<style>
</style>

@await Component.InvokeAsync("Banner")
<!--Giới thiệu|  Group1 là ID đặt trong form tuỳ chỉnh-->
@await Component.InvokeAsync("Intro", "Group1")
<!--Dịch vụ |  Group2 là ID đặt trong form tuỳ chỉnh-->
@await Component.InvokeAsync("Services", "Group2")
<!--Group 3|  Group3 là ID đặt trong form tuỳ chỉnh-->
@await Component.InvokeAsync("YearsNo", "Group3")
<!--Khách hàng tiêu biểu| Group4 là ID đặt trong form tuỳ chỉnh-->
@await Component.InvokeAsync("Customer", "Group4")

<div class="support-area bg-light pt-90 pb-90 mt-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="support-wrapper aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
                    <div class="section-title text-center">
                        <h1 class="title">Bạn có dự án nào không?</h1>
                        <p class="mt-5 mb-5 pb-3">Hoặc bạn muốn làm việc với chúng tôi hay muốn tìm hiểu thêm về những gì chúng tôi đã làm, chúng tôi rất muốn nghe ý kiến ​​của bạn.</p>
                    </div>
                    <div class="support-button">
                        <a class="btn btn-dark btn-hover-primary" asp-controller="Home" asp-action="Contact">Liên hệ với chúng tôi</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>